#!/bin/bash

APP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"

source $APP_ROOT/nodes

#Boron snapshot
DISTRIBUTION_SNAPSHOT_DOWNLOAD_URL='https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/integration/distribution-karaf/0.5.0-SNAPSHOT/distribution-karaf-0.5.0-20160829.225921-4700.zip'
DISTRIBUTION_RELEASE_DOWNLOAD_URL='https://nexus.opendaylight.org/content/repositories/public/org/opendaylight/integration/distribution-karaf/0.4.3-Beryllium-SR3/distribution-karaf-0.4.3-Beryllium-SR3.tar.gz'

DISTRO_ROOT=$APP_ROOT/distribution
DISTRO=$DISTRO_ROOT/odl

ODL_USER=admin
ODL_PASS=admin

BGP_PEER="$ROUTER_NODE_SJC"
LOCAL_AS=65504
REMOTE_AS=65504

DCLOUD=YES
DCLOUD_VPN_PID='/var/run/dcloud-vpn.pid'

FEATURES=odl-mdsal-apidocs,odl-bgpcep-bgp,odl-bgpcep-pcep
