#!/bin/bash

APP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"

#Boron snapshot
DISTRIBUTION_SNAPSHOT_DOWNLOAD_URL='https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/integration/distribution-karaf/0.6.0-SNAPSHOT/distribution-karaf-0.6.0-20160826.211023-360.tar.gz'
DISTRIBUTION_RELEASE_DOWNLOAD_URL='https://nexus.opendaylight.org/content/repositories/public/org/opendaylight/integration/distribution-karaf/0.4.3-Beryllium-SR3/distribution-karaf-0.4.3-Beryllium-SR3.tar.gz'

DISTRO_ROOT=$APP_ROOT/distribution
DISTRO=$DISTRO_ROOT/odl

ODL_USER=admin
ODL_PASS=admin

BGP_PEER=198.18.1.37
BGP_NODE=sjc
BGP_NEXT_HOP=198.18.1.1
LOCAL_AS=65504
REMOTE_AS=65504

NETCONF_PORT=830
NETCONF_USER=cisco
NETCONF_PASS=cisco

PORT_PREFIX=90

DCLOUD=YES
DCLOUD_VPN_PID='/var/run/dcloud-vpn.pid'

FEATURES=odl-mdsal-apidocs,odl-bgpcep-bgp,odl-bgpcep-pcep
