#!/bin/bash

source ./parameters
source ./vpn_credential

if [ -z "$DCLOUD_VPN_USRNAME" ]; then
    DCLOUD_VPN_USRNAME="$2"
fi
if [ -z "$DCLOUD_VPN_PASSWD" ]; then
    DCLOUD_VPN_PASSWD="$3"
fi

if [ -z "$DCLOUD_VPN_USRNAME" ]; then
    echo "VPN username cannot be empty"
    show_usage()
fi
if [ -z "$DCLOUD_VPN_PASSWD" ]; then
    echo "VPN password cannot be empty" 
    show_usage() 
fi

show_usage() {
	echo "usage $0 site lon|rtp|sng|chi [username] [password]"
	exit 1
}

echo $DCLOUD_VPN_PASSWD | sudo openconnect -u $DCLOUD_VPN_USRNAME --passwd-on-stdin https://dcloud-$1-anyconnect.cisco.com > vpn.log 2>&1 &

