#!/bin/bash
source ./parameters
echo $DISTRO
STOP_CMD="$DISTRO/bin/stop"

if [ -f "$STOP_CMD" ]; then
        $STOP_CMD
else
        echo "ODL hasn't been unpacked."
        exit 1
fi

while true;
do
        up=$(/bin/ps -ef | grep karaf | wc -l)
        if [ $up == 1 ]
        then
                echo "ODL has stopped"
                exit 0
        else
                echo "waiting for ODL to stop"
                sleep 5
        fi
done

